[gondor]
172.16.1.200

[arnor]
100.81.24.13

[lindon]
100.109.86.39

[bofur]
172.16.0.22

[bifur]
172.16.0.23

[bombur]
172.16.0.24

[ori]
172.16.0.25

[nori]
172.16.0.26

[dori]
172.16.0.27


[clients:children]
ori
nori
dori

[servers:children]
gondor
arnor
lindon

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
