version: '2'

services:
  plex:
    image: plexinc/pms-docker:latest
    volumes:
      - /mnt/tank/containers/plex:/config
      - /tmp/transcode:/transcode
      - /mnt/tank/media:/data
    restart: always
    environment:
      - PLEX_CLAIM: 
      - TZ: Europe/Stockholm
      - PLEX_UID: {{ plex_uid }}
      - PLEX_GID: {{ plex_gid }}
