version: '2'

services: 
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/tank/containers/rproxy/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/mnt/tank/containers/rproxy/traefik/rules.yml:/etc/traefik/rules.yml:ro"
      - "/mnt/tank/containers/rproxy/traefik/acme.json:/acme.json"
    networks:
      - web

  authelia:
    image: "authelia/authelia:latest"
    restart: unless-stopped
    ports:
      - "9091:9091"
    volumes:
      - "/mnt/tank/containers/rproxy/authelia/configuration.yml:/config/configuration.yml"
      - "/mnt/tank/containers/rproxy/authelia/users.yml:/config/users.yml"
    networks:
      - web
    environment:
      TZ: Stockholm/Europe

networks:
  web:
    external:
      name: "web"
