---
- name: Ensure old versions of Docker are not installed.
  apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ensure additional dependencies are installed.
  apt:
    name:
      - gnupg
      - curl
    state: present

- name: Ensure apt keyring folder eists.
  file:
    dest: "/etc/apt/keyrings"
    state: directory
    owner: root
    group: root

- name: Check if Docker apt key exists.
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_gpg

- name: Add Docker apt key.
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: not docker_gpg.stat.exists

- name: Add Docker repository.
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: true

- name: Install Docker (and Docker Compose).
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Docker daemon.json configuration.
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker

- name: Ensure docker daemon is running and started on boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure group "docker" exists with correct gid.
  group:
    name: docker
    state: present
    gid: 2000

- name: Ensure folder for docker containers exists.
  file:
    dest: "{{ container_path }}"
    state: directory
    owner: root
    group: root
